apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
  annotations:
      #prometheus.io/scrape: 'true'
      #prometheus.io/port:   '9093'
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector: 
    app: alertmanager
  type: LoadBalancer
  loadBalancerIP: 10.11.8.129
  ports:
    - port: 80
      targetPort: 9093
